version: '3.9'

services:
  db:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 5433:5432

  hhor:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always
    links:
      - "db:database"
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - ./credentials/keys.json:/app/credentials/keys.json