version: '3.9'

services:
  db:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 5432:5432

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass hhorredis