definitions:
  dto.DormDTO:
    properties:
      id:
        type: string
      lat:
        type: number
      long:
        type: number
      name:
        type: string
      picture:
        type: string
      starting_price:
        type: integer
      zone:
        type: string
    type: object
  dto.DormSuggestionDTO:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  dto.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  dto.LoginCredentialsDTO:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  model.AllDormFacility:
    properties:
      name:
        type: string
    type: object
  model.AllRoomFacility:
    properties:
      name:
        type: string
    type: object
  model.Dorm:
    properties:
      address:
        type: string
      description:
        type: string
      dorm_owner:
        $ref: '#/definitions/model.DormOwner'
      facilities:
        items:
          $ref: '#/definitions/model.AllDormFacility'
        type: array
      id:
        type: integer
      lat:
        type: number
      long:
        type: number
      name:
        type: string
      nearby_locations:
        items:
          $ref: '#/definitions/model.NearbyLocation'
        type: array
      pictures:
        items:
          $ref: '#/definitions/model.DormPicture'
        type: array
      rooms:
        items:
          $ref: '#/definitions/model.Room'
        type: array
      rules:
        type: string
      type:
        type: string
      zone:
        type: string
    type: object
  model.DormOwner:
    properties:
      email:
        type: string
      firstname:
        type: string
      id:
        type: integer
      lastname:
        type: string
    type: object
  model.DormPicture:
    properties:
      picture_url:
        type: string
    type: object
  model.Location:
    properties:
      id:
        type: integer
      lat:
        type: number
      long:
        type: number
      name:
        type: string
    type: object
  model.NearbyLocation:
    properties:
      distance:
        type: number
      location:
        $ref: '#/definitions/model.Location'
    type: object
  model.PetPicture:
    properties:
      picture_url:
        type: string
    type: object
  model.Room:
    properties:
      available:
        type: boolean
      capacity:
        type: integer
      description:
        type: string
      facilities:
        items:
          $ref: '#/definitions/model.AllRoomFacility'
        type: array
      id:
        type: integer
      name:
        type: string
      pictures:
        items:
          $ref: '#/definitions/model.RoomPicture'
        type: array
      price:
        type: integer
      size:
        type: number
    type: object
  model.RoomPicture:
    properties:
      picture_url:
        type: string
    type: object
  model.Student:
    properties:
      biography:
        type: string
      email:
        type: string
      facebook_url:
        type: string
      faculty:
        type: string
      firstname:
        type: string
      gender:
        type: string
      instagram_url:
        type: string
      lastname:
        type: string
      linkedin_url:
        type: string
      pet_habit:
        type: string
      pet_pictures:
        items:
          $ref: '#/definitions/model.PetPicture'
        type: array
      picture_url:
        type: string
      preferred_gender:
        type: string
      room_care_habit:
        type: string
      sleeping_habit:
        type: string
      smoke_habit:
        type: string
      student_id:
        type: string
      study_habit:
        type: string
      twitter_url:
        type: string
      year_of_study:
        type: integer
    type: object
info:
  contact: {}
paths:
  /auth/student/login:
    post:
      description: login
      parameters:
      - description: login credentials
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.LoginCredentialsDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: login
      tags:
      - auth
  /auth/student/register:
    post:
      consumes:
      - multipart/form-data
      description: register student account
      parameters:
      - in: formData
        name: email
        required: true
        type: string
      - in: formData
        name: faculty
        required: true
        type: string
      - in: formData
        name: firstname
        required: true
        type: string
      - in: formData
        name: gender
        required: true
        type: string
      - in: formData
        name: lastname
        required: true
        type: string
      - in: formData
        name: password
        required: true
        type: string
      - in: formData
        name: student_id
        required: true
        type: string
      - in: formData
        name: year_of_study
        required: true
        type: integer
      - description: profile picture
        in: formData
        name: profile_picture
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: register student account
      tags:
      - auth
  /dorm:
    get:
      consumes:
      - application/json
      description: returns list of dorms filter by dorm type, zone,capacity, location,
        dorm and room facilities
      parameters:
      - in: query
        name: capacity
        type: integer
      - in: query
        items:
          type: string
        name: dorm_facilities
        type: array
      - in: query
        name: lat
        type: number
      - in: query
        name: long
        type: number
      - in: query
        name: lower_price
        type: integer
      - in: query
        name: name
        type: string
      - in: query
        items:
          type: string
        name: room_facilities
        type: array
      - in: query
        items:
          type: string
        name: type
        type: array
      - in: query
        name: upper_price
        type: integer
      - in: query
        name: zone
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.DormDTO'
            type: array
      summary: get list of dorms
      tags:
      - dorm
  /dorm/{id}:
    get:
      description: returns dorm details
      parameters:
      - description: Dorm ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Dorm'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: get dorm details from dorm id
      tags:
      - dorm
  /dorm/facility:
    get:
      description: returns list of dorm facilities
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: get dorm facilities
      tags:
      - dorm
  /dorm/suggest/{letter}:
    get:
      description: returns list of dorm names from first letter
      parameters:
      - description: First Letter
        in: path
        name: letter
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.DormSuggestionDTO'
            type: array
      summary: get dorm names from first letter
      tags:
      - dorm
  /dorm/zone:
    get:
      description: returns list of dorm zones
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: get dorm zones
      tags:
      - dorm
  /room/facility:
    get:
      description: returns list of room facilities
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: get room facilities
      tags:
      - room
  /student:
    patch:
      consumes:
      - multipart/form-data
      description: update student detail
      parameters:
      - in: formData
        name: biography
        type: string
      - in: formData
        name: email
        required: true
        type: string
      - in: formData
        name: facebookUrl
        type: string
      - in: formData
        name: instagramUrl
        type: string
      - in: formData
        name: linkedinUrl
        type: string
      - in: formData
        name: twitterUrl
        type: string
      - description: profile picture
        in: formData
        name: profile_picture
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: update student detail
      tags:
      - student
  /student/{email}:
    get:
      description: returns student profile
      parameters:
      - description: Student Email
        in: path
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Student'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: get student profile
      tags:
      - student
swagger: "2.0"
